config/routes.rb
Rails.application.routes.draw do
  resources :data_sources
  resources :data_summaries
  resources :model_databases
  resources :tanks
  resources :pumps
  resources :overflows
  resources :cellars
  resources :incidents
  resources :connections
  resources :flows
  resources :backgrounds
  resources :reports, except: [:edit] do
    resources :report_wizard, controller: 'reports/report_wizard'
  end
  devise_for :users
  resources :users, only: [:index]
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  has_many :flows, :dependent => :delete_all
  has_many :connections, :dependent => :delete_all
  has_many :incidents, :dependent => :delete_all
  has_many :cellars, :dependent => :delete_all
  has_many :overflows, :dependent => :delete_all
  has_many :pumps, :dependent => :delete_all
  has_many :tanks, :dependent => :delete_all
  has_many :data_sources, :dependent => :delete_all
  has_one :model_database, dependent: :destroy
  has_one :data_summary, dependent: :destroy
  has_one :executive, dependent: :destroy
  has_one :background, dependent: :destroy

  validates :project_name, presence: true

  accepts_nested_attributes_for :executive,
                                allow_destroy: true

  accepts_nested_attributes_for :background,
                                allow_destroy: true

  accepts_nested_attributes_for :flows,
                                allow_destroy: true

  accepts_nested_attributes_for :connections,
                                allow_destroy: true

  accepts_nested_attributes_for :incidents,
                                allow_destroy: true

  accepts_nested_attributes_for :cellars,
                                allow_destroy: true

  accepts_nested_attributes_for :overflows,
                                allow_destroy: true

  accepts_nested_attributes_for :pumps,
                                allow_destroy: true

  accepts_nested_attributes_for :tanks,
                                allow_destroy: true

  accepts_nested_attributes_for :model_database,
                                allow_destroy: true

  accepts_nested_attributes_for :data_summary,
                                allow_destroy: true

  accepts_nested_attributes_for :data_sources,
                                allow_destroy: true

  has_rich_text :executive_summary
  has_rich_text :project_background
  has_rich_text :background_intro
  has_rich_text :project_objective
  has_rich_text :proposed_developments
  has_rich_text :catchment_details
  has_rich_text :data_assessment
  has_rich_text :conclusion
  has_rich_text :catchment_tank
  has_rich_text :cellared_property
  has_rich_text :catchment_overflow
  has_rich_text :pumping_station
  has_rich_text :flooding_locations
end

app/controllers/report_wizard_controller.rb
class ReportWizardController < ApplicationController
  include Wicked::Wizard
  before_action :set_progress, only: [:show]

  steps :project_information, :executive_summary

  def show
    # case step
    # when :find_friends
    #   @friends = @user.find_friends
    # end
    render_wizard
  end

  def finish_wizard_path
    root_path
  end

  private 

  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

end

app/controllers/reports/report_wizard_controller.rb
class Reports::ReportWizardController < ApplicationController
  include Wicked::Wizard
  before_action :set_progress, only: [:show, :update]
  before_action :set_report, only: [:show, :update, :finish_wizard_path]

  steps :project_information, :executive_summary, :project_background, :project_objective, :proposed_developments, :catchment_details, :data_assessment, :conclusion

  def show
      case step
      when :project_information
      when :executive_summary
      when :project_background
      when :project_objective
      when :proposed_developments
      when :catchment_details
      when :data_assessment
      when :conclusion
    end
    render_wizard
  end

  def update
    case step
    when :project_information
      @report.update(report_params)
    when :executive_summary
      @report.update(report_params)
    when :executive_summary
      @report.update(report_params)
    when :project_background
      @report.update(report_params)
    when :project_objective
      @report.update(report_params)
    when :proposed_developments
      @report.update(report_params)
    when :catchment_details
      @report.update(report_params)
    when :data_assessment
      @report.update(report_params)
    when :conclusion
      @report.update(report_params)
    end
    redirect_to request.referrer
    #render_wizard @report
  end

  def finish_wizard_path
    report_path(@report)
  end

  private 

  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

  def set_report
    @report = Report.find(params[:report_id])
  end

  def report_params
    params.require(:report).permit(:project_name, :project_number, :document_title, :document_number, :document_status, :date, :revision, :approved_by,
                                  :client_name, :client_number, :project_manager, :author, :checked_by, :description, :executive_summary, :background_intro,
                                  :project_background, :project_objective, :proposed_developments, :catchment_details, :data_assessment, :conclusion, :flooding_locations,
                                  :cellared_property, :pumping_station, :catchment_overflow, :catchment_tank,
                                  executive_attributes: [:id, :project_name, :project_number, :potential_impact, :date], 
                                  background_attributes: [:id, :site_name, :location, :property_count, :site_type],
                                  flows_attributes: [:id, :flow_modelled, :includes, :comments],
                                  connections_attributes: [:id, :development, :dwf, :thirty_year, :node_ref, :freeboard, :receiving_sewer, :pfc, :pipe, :peak_flow, :pumped],
                                  incidents_attributes: [:id, :location, :postcode, :ngr, :hfrr, :historical_flooding, :wirs, :nearest_node, :modelled_risk, :comments],
                                  cellars_attributes: [:id, :location, :postcode, :ngr, :flooding_register, :wirs_register, :freeboard, :nearest_node, :comments],
                                  overflows_attributes: [:id, :cso_name, :permit, :model, :edm_annual_spill_freq, :edm_annual_spill_duration, :edm_bathing_spill_freq, :edm_bathing_spill_duration, :model_annual_spill_freq, :model_annual_spill_duration, :model_annual_spill_volume, :model_bathing_spill_freq, :model_bathing_spill_duration, :model_bathing_spill_volume, :comments],
                                  pumps_attributes: [:id, :station_ref, :name, :overflow_ref, :permitted_rate, :modelled_rate, :run_time, :comments],
                                  tanks_attributes: [:id, :tank_ref, :name, :overflow_ref, :online, :permitted_storage, :effective_storage, :annual_volume, :comments],
                                  model_database_attributes: [:id, :model_type, :subcatchment_review, :contributing_areas, :flooding_representation, :soil_type, :runoff_model, :ancillaries_wwtw, :ancillaries_cso, :ancillaries_tanks, :ancillaries_pumps, :rainfall_data, :model_update, :model_suitable],
                                  data_summary_attributes: [:id, :summary_1, :summary_2, :summary_3, :summary_4, :summary_5, :summary_6],
                                  data_sources_attributes: [:id, :data_required, :provided, :file_name]
                                  )
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]

  def index
    #@reports = Report.all
    @q = Report.ransack(params[:q])
    @reports = @q.result(distinct: true)
  end

  def show
    @page_title = @report.document_title
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user
    respond_to do |format|
      if @report.save
        format.html { redirect_to report_report_wizard_index_path(@report) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @report.update(report_params)
  #       format.html { redirect_to report_report_wizard_index_path(@report), notice: "Report was successfully updated." }
  #       format.json { render :show, status: :ok, location: @report }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @report.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:project_name, :project_number, :document_title, :document_number, :document_status, :date, :revision, :approved_by,
                                    :client_name, :client_number, :project_manager, :author, :checked_by, :description, :executive_summary, :background_intro,
                                    :project_background, :project_objective, :proposed_developments, :catchment_details, :data_assessment, :conclusion, :flooding_locations,
                                    :cellared_property, :pumping_station, :catchment_overflow, :catchment_tank,
                                    executive_attributes: [:id, :project_name, :project_number, :potential_impact, :date], 
                                    background_attributes: [:id, :site_name, :location, :property_count, :site_type],
                                    flows_attributes: [:id, :flow_modelled, :includes, :comments],
                                    connections_attributes: [:id, :development, :dwf, :thirty_year, :node_ref, :freeboard, :receiving_sewer, :pfc, :pipe, :peak_flow, :pumped],
                                    incidents_attributes: [:id, :location, :postcode, :ngr, :hfrr, :historical_flooding, :wirs, :nearest_node, :modelled_risk, :comments],
                                    cellars_attributes: [:id, :location, :postcode, :ngr, :flooding_register, :wirs_register, :freeboard, :nearest_node, :comments],
                                    overflows_attributes: [:id, :cso_name, :permit, :model, :edm_annual_spill_freq, :edm_annual_spill_duration, :edm_bathing_spill_freq, :edm_bathing_spill_duration, :model_annual_spill_freq, :model_annual_spill_duration, :model_annual_spill_volume, :model_bathing_spill_freq, :model_bathing_spill_duration, :model_bathing_spill_volume, :comments],
                                    pumps_attributes: [:id, :station_ref, :name, :overflow_ref, :permitted_rate, :modelled_rate, :run_time, :comments],
                                    tanks_attributes: [:id, :tank_ref, :name, :overflow_ref, :online, :permitted_storage, :effective_storage, :annual_volume, :comments],
                                    model_database_attributes: [:id, :model_type, :subcatchment_review, :contributing_areas, :flooding_representation, :soil_type, :runoff_model, :ancillaries_wwtw, :ancillaries_cso, :ancillaries_tanks, :ancillaries_pumps, :rainfall_data, :model_update, :model_suitable],
                                    data_summary_attributes: [:id, :summary_1, :summary_2, :summary_3, :summary_4, :summary_5, :summary_6],
                                    data_sources_attributes: [:id, :data_required, :provided, :file_name]
                                    )
    end
end

app/helpers/report_wizard_helper.rb
module ReportWizardHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/report_wizard/_connection_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small">Development</label>
    <%= f.text_field :development, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">DWF(l/s)</label>
    <%= f.text_field :dwf, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">30-Year(l/s)</label>
    <%= f.text_field :thirty_year, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Node Ref</label>
    <%= f.text_field :node_ref, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Freeboard(m)</label>
    <%= f.text_field :freeboard, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Receiving Sewer Dia.(mm)</label>
    <%= f.text_field :receiving_sewer, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">PFC(l/s)</label>
    <%= f.text_field :pfc, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Pipe RPA(l/s)</label>
    <%= f.text_field :pipe, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">M30 Peak Flow(l/s)</label>
    <%= f.text_field :peak_flow, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Pumped/Gravity(l/s)</label>
    <%= f.text_field :pumped, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= link_to_remove_association 'Delete Row', f, class: "delete-row" %>
  </div>
</div></br>

app/views/reports/report_wizard/_data_source_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small-low">Data Required</label>
    <%= f.text_field :data_required, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Provided (Y/N)</label>
    <%= f.text_field :provided, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">File Name</label>
    <%= f.text_field :file_name, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= link_to_remove_association 'Delete Row', f, class: "delete-row" %>
  </div>
</div></br>

app/views/reports/report_wizard/_executive_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <%= f.label :project_name, class: "head-small" %>
    <%= f.text_field :project_name, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= f.label :project_number, class: "head-small" %>
    <%= f.text_field :project_number, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= f.label :potential_impact, class: "head-small" %>
    <%= f.text_field :potential_impact, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= f.label :date, class: "head-small" %>
    <%= f.text_field :date, class: 'form-control' %>
  </div>
</div></br>

app/views/reports/report_wizard/_flow_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small">Flows to be modelled</label>
    <%= f.text_field :flow_modelled, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Yes/No</label>
    <%= f.text_field :includes, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Comments</label>
    <%= f.text_field :comments, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= link_to_remove_association 'Delete Row', f, class: "delete-row" %>
  </div>
</div></br>

app/views/reports/report_wizard/_incident_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small">Location</label>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Post Code</label>
    <%= f.text_field :postcode, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">NGR</label>
    <%= f.text_field :ngr, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">HFRR Property (Y/N)</label>
    <%= f.text_field :hfrr, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Historical Flooding Property</label>
    <%= f.text_field :historical_flooding, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">WIRS/INS Incidents (Total No.)</label>
    <%= f.text_field :wirs, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Nearest Model Node</label>
    <%= f.text_field :nearest_node, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Modelled Risk RP</label>
    <%= f.text_field :modelled_risk, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Comments</label>
    <%= f.text_field :comments, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= link_to_remove_association 'Delete Row', f, class: "delete-row" %>
  </div>
</div></br>

app/views/reports/report_wizard/_model_database_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small-low">Model Type (I, II, III)</label>
    <%= f.text_area :model_type, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Subcatchment Review</label>
    <%= f.text_area :subcatchment_review, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Contributing Areas</label>
    <%= f.text_area :contributing_areas, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Flooding Representation</label>
    <%= f.text_area :flooding_representation, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Soil Type</label>
    <%= f.text_area :soil_type, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Runoff Model</label>
    <%= f.text_area :runoff_model, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Sewer Ancillaries – WwTW</label>
    <%= f.text_area :ancillaries_wwtw, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Sewer Ancillaries – CSO’s</label>
    <%= f.text_area :ancillaries_cso, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Sewer Ancillaries - Tanks</label>
    <%= f.text_area :ancillaries_tanks, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Sewer Ancillaries – Pumping Stations</label>
    <%= f.text_area :ancillaries_pumps, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">FEH Rainfall Data</label>
    <%= f.text_area :rainfall_data, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Is model update required prior to undertaking a full DIA assessment?</label>
    <%= f.text_area :model_update, class: 'form-control text-area-sm' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small-low">Is the current model deemed suitable to undertake a full DIA?</label>
    <%= f.text_area :model_suitable, class: 'form-control text-area-sm' %>
  </div>
</div>

app/views/reports/report_wizard/_navigation_fields.html.erb
<hr style="height: 1px; background-color: black; width:100%;">

<%= link_to previous_wizard_path do %>
  <div class="btn btn-inverse nav-left">
    <div><i class="fas fa-angle-double-left "></i></div>
  </div>
<% end %>

<%= link_to next_wizard_path do %>
  <div class="btn btn-inverse nav-right">
    <div><i class="fas fa-angle-double-right"></i></div>
  </div>
<% end %>

app/views/reports/report_wizard/_progress.html.erb
<div class="home-btn"
<%= link_to "/", class: "home-icon-header" do %>
  <i class="fas fa-home home-icon-page"></i>
<% end %>
</div><br/>
<div class="progress">
  <div class="bar" style="width: <%= @progress %>%"></div>
</div>

app/views/reports/report_wizard/_pump_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small">Pumping Station Ref.</label>
    <%= f.text_field :station_ref, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Linked Overflow Ref.</label>
    <%= f.text_field :overflow_ref, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Permitted Pump Rate (l/s)</label>
    <%= f.text_field :permitted_rate, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Total Modelled Pump Rate (l/s)</label>
    <%= f.text_field :modelled_rate, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Annual Pump Run Time (hours)</label>
    <%= f.text_field :run_time, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Comments</label>
    <%= f.text_field :comments, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= link_to_remove_association 'Delete Row', f, class: "delete-row" %>
  </div>
</div></br>

app/views/reports/report_wizard/_steps.html.erb
<div class="steps">
  <%= wizard_steps.index(step) + 1 %>/
  <%= wizard_steps.count %>
</div>

app/views/reports/report_wizard/_tank_fields.html.erb
<div class="hidden-container nested-fields shadow rounded">
  <div class="form-group hidden-field">
    <label class="head-small">Tank Ref.</label>
    <%= f.text_field :tank_ref, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Name</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Linked Overflow Ref.</label>
    <%= f.text_field :overflow_ref, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Online/Offline</label>
    <%= f.text_field :online, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Permitted Storage Volume (m3)</label>
    <%= f.text_field :permitted_storage, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Effective Storage Volume (m3)</label>
    <%= f.text_field :effective_storage, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Annual Volume To Tank (m3)</label>
    <%= f.text_field :annual_volume, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <label class="head-small">Comments</label>
    <%= f.text_field :comments, class: 'form-control' %>
  </div>
  <div class="form-group hidden-field">
    <%= link_to_remove_association 'Delete Row', f, class: "delete-row" %>
  </div>
</div></br>

app/views/reports/report_wizard/conclusion.html.erb
<div class= "form-container">
  <%= render 'progress' %>
  <div class="heading">
    <%= render 'steps' %>
    <h2 class="head-large">Conclusion</h2>
  </div>

  <%= render layout: 'text_area' do |f| %>
      <%= f.rich_text_area :conclusion, class: "text-area" %>
  <% end %></br></br>
 
  <%= render 'navigation_fields' %>
</div>

app/views/reports/report_wizard/data_assessment.html.erb
<div class= "form-container">
  <%= render 'progress' %>
  <div class="heading">
    <%= render 'steps' %> 
    <h2 class="head-large">Data Assessment</h2>
  </div>
  <%= form_for @report, url: report_report_wizard_path, method: :put do |f| %>
    <div class="text-container">
      <%= f.rich_text_area :data_assessment, class: "form-control text-area" %>
    </div></br>

    <h3 class="head-md-dark">Summary of Data Gathered</h3></br>
    <div>
      <%= f.fields_for :data_sources do |source_form| %>
        <div class="rows-container">
          <%= render 'data_source_fields', f: source_form %>
        </div>
      <% end %>
    </div>
    
    <div class="row-buttons">
      <div>
        <%= link_to_add_association 'Add Row to Data Gathered Table', f, :data_sources, class: "btn-reserved", style: "background-color: #262626; border: none; color: #fff; float: right;" %>
      </div>
    <div></br></br>

    <h3 class="head-md-dark">Model Fit For Purpose (FFP) Review</h3></br>
    <div>
      <%= f.fields_for :model_database_attributes, @report.model_database do |database_form| %>
        <div class="rows-container">
          <%= render 'model_database_fields', f: database_form %>
        </div>
      <% end %>
    </div></br>

    <h3 class="head-md-dark">Database Summary</h3></br>
    <div>
      <%= f.fields_for :data_summary_attributes, @report.data_summary do |summary_form| %>
        <div class="rows-container">
          <%= render 'data_summary_fields', f: summary_form %>
        </div>
      <% end %>
    </div></br>
    
    <div class="row-buttons">
      <div>
        <%= f.submit "Save Changes" , class: "btn-reserved", style: "background-color: #262626; border: none; color: #fff; float: left;"%>
      </div>
    <div>
  <% end %>

  <div class="nav-field">
    <%= render 'navigation_fields' %>
  </div>

</div>

app/views/reports/report_wizard/project_information.html.erb
<div class= "form-container">
  <%= render 'progress' %>
  <div class="heading">
    <%= render 'steps' %> 
    <h2 class="head-large">Project Information</h2>
  </div>
  <div>
    <%= form_for @report, url: report_report_wizard_path, method: :put do |f| %>
      <div class="field form-field">
        <%= f.label :project_number, class: "head-small form-label" %>
        <%= f.text_field :project_number, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :document_title, class: "head-small form-label" %>
        <%= f.text_field :document_title, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :document_number, class: "head-small form-label" %>
        <%= f.text_field :document_number, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :document_status, class: "head-small form-label" %>
        <%= f.text_field :document_status, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :date, class: "head-small form-label" %>
        <%= f.text_field :date, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :client_name, class: "head-small form-label" %>
        <%= f.text_field :client_name, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :client_number, class: "head-small form-label" %>
        <%= f.text_field :client_number, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :project_manager, class: "head-small form-label" %>
        <%= f.text_field :project_manager, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :author, class: "head-small form-label" %>
        <%= f.text_field :author, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :checked_by, class: "head-small form-label" %>
        <%= f.text_field :checked_by, class: "form-input" %>
      </div>
      <div class="field form-field">
        <label class="head-small form-label">Reviewed By</label>
        <%= f.text_field :approved_by, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :revision, class: "head-small form-label" %>
        <%= f.text_field :revision, class: "form-input" %>
      </div>
      <div class="field form-field">
        <%= f.label :description, class: "head-small form-label" %>
        <%= f.text_field :description, class: "form-input" %>
      </div>

      <div>
        <%= f.submit "Save Changes" , class: "btn-reserved", style: "background-color: #262626; border: none; color: #fff; float: left;"%>
      </div>
    <% end %>
  </div></br></br>

  <hr style="height: .1rem; background-color: #262626; width:100%;">

  <%= link_to next_wizard_path do %>
    <div class="btn btn-inverse nav-left">
      <div>
        <%= link_to 'Cancel', root_path, style: "background-color: #262626; border: none; color: #fff;" %>
      </div>
    </div>
  <% end %>

  <%= link_to next_wizard_path do %>
    <div class="btn btn-inverse nav-right">
      <div><i class="fas fa-angle-double-right"></i></div>
    </div>
  <% end %>
</div>