config/routes.rb
Rails.application.routes.draw do
  resources :data_sources
  resources :data_summaries
  resources :model_databases
  resources :tanks
  resources :pumps
  resources :overflows
  resources :cellars
  resources :incidents
  resources :connections
  resources :flows
  resources :backgrounds
  resources :reports, except: [:edit] do
    resources :report_wizard, controller: 'reports/report_wizard'
  end
  devise_for :users
  resources :users, only: [:index]
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :report
end

app/models/cellar.rb
class Cellar < ApplicationRecord
  belongs_to :report
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :report
end

app/models/data_source.rb
class DataSource < ApplicationRecord
  belongs_to :report
end

app/models/data_summary.rb
class DataSummary < ApplicationRecord
  belongs_to :report
end

app/models/executive.rb
class Executive < ApplicationRecord
  belongs_to :report
end

app/models/flow.rb
class Flow < ApplicationRecord
  belongs_to :report
end

app/models/incident.rb
class Incident < ApplicationRecord
  belongs_to :report
end

app/models/model_database.rb
class ModelDatabase < ApplicationRecord
  belongs_to :report
end

app/models/overflow.rb
class Overflow < ApplicationRecord
  belongs_to :report
end

app/models/pump.rb
class Pump < ApplicationRecord
  belongs_to :report
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  has_many :flows, :dependent => :delete_all
  has_many :connections, :dependent => :delete_all
  has_many :incidents, :dependent => :delete_all
  has_many :cellars, :dependent => :delete_all
  has_many :overflows, :dependent => :delete_all
  has_many :pumps, :dependent => :delete_all
  has_many :tanks, :dependent => :delete_all
  has_many :data_sources, :dependent => :delete_all
  has_one :model_database, dependent: :destroy
  has_one :data_summary, dependent: :destroy
  has_one :executive, dependent: :destroy
  has_one :background, dependent: :destroy

  validates :project_name, presence: true

  accepts_nested_attributes_for :executive,
                                allow_destroy: true

  accepts_nested_attributes_for :background,
                                allow_destroy: true

  accepts_nested_attributes_for :flows,
                                allow_destroy: true

  accepts_nested_attributes_for :connections,
                                allow_destroy: true

  accepts_nested_attributes_for :incidents,
                                allow_destroy: true

  accepts_nested_attributes_for :cellars,
                                allow_destroy: true

  accepts_nested_attributes_for :overflows,
                                allow_destroy: true

  accepts_nested_attributes_for :pumps,
                                allow_destroy: true

  accepts_nested_attributes_for :tanks,
                                allow_destroy: true

  accepts_nested_attributes_for :model_database,
                                allow_destroy: true

  accepts_nested_attributes_for :data_summary,
                                allow_destroy: true

  accepts_nested_attributes_for :data_sources,
                                allow_destroy: true

  has_rich_text :executive_summary
  has_rich_text :project_background
  has_rich_text :background_intro
  has_rich_text :project_objective
  has_rich_text :proposed_developments
  has_rich_text :catchment_details
  has_rich_text :data_assessment
  has_rich_text :conclusion
  has_rich_text :catchment_tank
  has_rich_text :cellared_property
  has_rich_text :catchment_overflow
  has_rich_text :pumping_station
  has_rich_text :flooding_locations
end

app/models/tank.rb
class Tank < ApplicationRecord
  belongs_to :report
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :reports

  def username
    self.email.split(/@/).first
  end

  def to_s
    email
  end


  def first_name
    self.username.split('.').first
  end

  def last_name
    self.username.split('.').last
  end


  has_many :reports
end

app/helpers/cellars_helper.rb
module CellarsHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pumps_helper.rb
module PumpsHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>', '', {
        "closeButton": true,
        "positionClass": "toast-top-right", 
        "onclick": null, 
        "showDuration": "300", 
        "hideDuration": "1000", 
        "timeOut": "5000", 
        "extendedTimeOut": "1000", 
        "showEasing": "swing", 
        "hideEasing": "linear", 
        "showMethod": "fadeIn", 
        "progressBar": true,
        "hideMethod": "fadeOut" }
      );
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Stanley Akyea">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Jacobs Report Card · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbars/">

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
  </head>
  <body>
    
<main>
  <nav class="navbar navbar-fixed-top navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="home-btn"
        <%= link_to root_url, class: "home-icon-header" do %>
          <i class="fas fa-home home-icon"></i>
        <% end %>
      
        <%= image_tag("jacobs-preview.png", class: "header-logo", id: "navbar-logo") %>
      </div>
      <button class="hamburger navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample01">
        <ul class="navbar-nav me-auto mb-2">
          <% if (!user_signed_in?) %>
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link active" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'My Reports', reports_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'All Reports', reports_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'All Users', users_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link active" %>
            </li>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</main>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>